### ISSUE TITLE
Any reason to have the "internal" module?

### ISSUE THREAD

**Issue by mrkkrp** [zohl/servant-auth-cookie#10]
You have two modules but the public one just exports things from the internal one. Let's move everything from the internal one and we can export things just as well. What do you think?

**Comment by mrkkrp** [comment]
Also, since internal one is in `exported-modules`, I don't any point in it at all.

**Comment by mrkkrp** [comment]
BTW, `extensions` is obsolete, you should write `default-extensions` now.

**Comment by mrkkrp** [comment]
Don't fix it, I already fixed it in the PR I'm preparing.

**Comment by zohl** [comment]
That was made intentionally. There are some auxiliary declarations that shouldn't bother an end-user. This is why I do not export them in `Servant.Server.Experimental.Auth.Cookie`.
And at the same time I need to test (and possibly benchmark) those auxiliary functions, so I export them too.

The reason behind two modules is "tagging" what is public and what is not. Indeed, an end-user can import "private" functions, but this will not be by accident, as the module name says `Internal`.

This is claimed to be ["the usual convention"](https://stackoverflow.com/questions/14379185/function-privacy-and-unit-testing-haskell) and I saw few libraries with such an approach.

**Comment by mrkkrp** [comment]
OK, I personally prefer keep internal stuff inaccessible to end users so they *can't* make the mistake of using it. (I've seen some examples of code that uses “internal” modules, and not for testing.)

Ideally, everything should be testable via testing of public API, because that's what matters anyway. I can imagine it's easier to test some specific helpers to make sure they are correct, though, so let's close it.
