### ISSUE TITLE
The documentation for the latest version of this package is missing on Hackage.

### ISSUE THREAD

**Issue by expipiplus1** [zohl/servant-auth-cookie#19]
The documentation for the latest version of this package is missing on Hackage. They've been pending on Hackage for some time, this usually indicated that Hackage wasn't able to build the package.

Is it possible for you to manually upload the package using `cabal upload --doc`, please?

Thanks!

**Comment by mrkkrp** [comment]
Generation of docs on Hackage has never been reliable. Please use Stackage instead: https://www.stackage.org/package/servant-auth-cookie.

**Comment by mrkkrp** [comment]
And for the latest version: https://www.stackage.org/nightly-2016-10-29/package/servant-auth-cookie-0.4

**Comment by expipiplus1** [comment]
Yeah, it's a shame. I think that work is being done to improve the state of documentation building.

It's nice to use Hackage for browsing all documentation and not have to remember which website to use for each package.

**Comment by zohl** [comment]
Hello,

sorry for the delay and thanks for the notice!

The docs have been uploaded:
https://hackage.haskell.org/package/servant-auth-cookie-0.4/docs/Servant-Server-Experimental-Auth-Cookie.html
