### ISSUE TITLE
Stackage LTS: Relaxing bounds on cryptonite

### ISSUE THREAD

**Issue by lwm** [zohl/servant-auth-cookie#24]
Hi @zohl, I am currently trying to build an LTS on Stackage and running into a strict upper bound issue with servant-auth-cookie. Would you be able to relax the upper bound of cryptonite to <=0.21?

I'm currently seeing:
```
stackage-curator: cryptonite-0.21 (Vincent Hanquez @vincenthz) is out of bounds for: 
- [ ] servant-auth-cookie-0.3.2 (>=0.14 && <=0.20). Al Zohali <zohl@fmap.me> @zohl. @zohl. Used by: library, executable, test-suite, benchmark
```

**Comment by zohl** [comment]
Hello,

Sure, I've uploaded version with relaxed upper bound. [1]
Stackage LTS should pick it up during a week. If you don't want to wait, you can try to use `servant-auth-cookie-0.4.2`: there haven't been made many changes yet and they are not that radical to expect everything to break ;)

[1] https://hackage.haskell.org/package/servant-auth-cookie-0.3.3

**Comment by lwm** [comment]
Thanks @zohl! We tried with `0.4.2` but it was bringing too many new constraints. Great that you made the release, I'll fire up a new build then :+1:
