### ISSUE TITLE
Drains /dev/random on every request

### ISSUE THREAD

**Issue by liskin** [zohl/servant-auth-cookie#25]
See https://github.com/zohl/servant-auth-cookie/commit/fdd3fa7c7c50bfd867b49387cd24414071b12efe#commitcomment-20292182

**Comment by zohl** [comment]
Hi @liskin,

Thank you! You're right, I checked it and, indeed, a new state for `ServerKey` is created every time we're trying to get it.
I fixed it with binary mutex (`MVar ()`) and it seems to work OK.

However, the example is broken and I'm going to repair it, so I can check that fix thoroughly. Let's leave the issue open for a while.

**Comment by liskin** [comment]
Cool. You could use bracket instead of a manual take/put, and I think it'd be safe enough to do this only inside of `if expired`.

**Comment by zohl** [comment]
Yes, `bracket` will be very handy here.

But I don't think it would be safe to guard only `if expired` block for the following reason.
Let's consider the case: two threads calls `getServerKey` and the key has already expired. Here is one of possible timelines (names of the variables are according to this [1] commit):

| time | 1st thread                      | 2nd thread                      |
|:---: | :------------------------------ | :------------------------------ |
| 0    | `curState <- readIORef skState` |                                 |
| 1    |                                 | `curState <- readIORef skState` |
| 2    | `takeMVar skLock`               |                                 |
| 3    | `writeIORef skState newState`   |                                 |
| 4    | `putMVar skLock`                |                                 |
| 5    |                                 | `takeMVar skLock`               |
| 6    |                                 | `writeIORef skState newState`   |
| 7    |                                 | `putMVar skLock`                |
| 8    | `return sksBytes`               |                                 |
| 9    |                                 | `return sksBytes`               |

The key returned in the first thread will not be correct and therefore authentication process for one of the users will fail.

We have to block `skState` before we read it, so this case will not happen.
On the bright side we can take a shortcut if `skMaxAge` is `Nothing`: this means the key will not be overwritten, so we can read it in non-blocking mode.

[1] https://github.com/zohl/servant-auth-cookie/commit/4c1e605a16c28d733543a46710dd43792c42aedd

**Comment by liskin** [comment]
Oh, right you are. You'd have to recheck (once obtaining the lock) whether some other thread already managed to update the key and if so, just use it. At this point it's probably easier to just rewrite it using STM instead of manually coding this logic.

Anyway, my main point was meant to be that taking a lock at every request won't scale. It's not nearly as bad as draining /dev/random, but if this is ever used in a production system, it might be an issue. I won't have such a system in the near future and if I every did have one, I'd probably be paid to create a pull request that creates this, so... if this doesn't bother you yet, feel free to ignore it. :-)

**Comment by zohl** [comment]
Thank you for the pointing this out, if STM plays better here I'll definitely give it a try.
But that's another story, another issue... I guess we can close this one ;)

**Comment by liskin** [comment]
Yeah, in STM you just say atomicaly { read; if expired { do something; write } } and if the var is already changed when writing, the whole transaction restarts, does read again and hopefully doesn't go into the if expired branch at all.

(And there's readTVarIO that's supposed to be even faster than atomically { read } but you'd need to do the normal read again in the transaction. That's a microoptimization.)

**Comment by liskin** [comment]
But now that I think about it, you won't be able to read the /dev/random inside of an STM transaction. That complicates things. :-(

**Comment by liskin** [comment]
Nevermind then, I need to get some sleep and this whole mental exercise is rather preliminary. :-)

**Comment by zohl** [comment]
Indeed, STM with `IO` don't seem to get along well (`unsafeIOToSTM` doesn't count :-).
However, we can switch to optimistic locking [1] and have similar benefits and tradeoffs as in STM case.

Given that we can't use STM, I think it's close enough to the desired result. We do not have locks anymore and `/dev/random` is drained pretty rare (`n` extra drains when `n + 1` users access the website at the moment of the expiration of the key).

[1] https://github.com/zohl/servant-auth-cookie/commit/8f81330358ca6977f7800e7eef9cafe57e4eb0f0

**Comment by liskin** [comment]
Cool!
