### ISSUE TITLE
Add to Stackage

### ISSUE THREAD

**Issue by mrkkrp** [zohl/servant-auth-cookie#3]
Does it make sense to add this to Stackage?

**Comment by mrkkrp** [comment]
Hi, I think you can bump version to 0.3.0 for example and publish it on Hackage, we can then add it to Stackage.

**Comment by zohl** [comment]
Hello,

I released and published it, please find it [here](https://hackage.haskell.org/package/servant-auth-cookie-0.3.0.0)

**Comment by mrkkrp** [comment]
Thank you. Can you add it to Stackage? It's very simple. You go to https://github.com/fpco/stackage and clone the repo. Then you edit the `build-constraints.yaml` file and add yourself just like other people in the list. You can find me in the list and see how my packages are added for reference. Then you open a PR with title like “Add the `servant-auth-cookie` package”, and that's it. They will merge it.

**Comment by zohl** [comment]
I submited the PR and will check tomorrow the result. Thank you for guidance!

**Comment by zohl** [comment]
Looks like the dependencies is out of sync a little bit. I've pushed the change to `nightly` branch, and [here](https://travis-ci.org/fpco/stackage/builds/147880728) is a travis log. Can we adjust versions of the packages, or is there a different kind of problem?

**Comment by mrkkrp** [comment]
You can you please reopen the PR? These messages has nothing to do with `servant-auth-cookie`.

**Comment by zohl** [comment]
Sure, reopened.

**Comment by mrkkrp** [comment]
I think we can close this now.
