### ISSUE TITLE
Can't create endpoint for checking authentication

### ISSUE THREAD

**Issue by mschristiansen** [zohl/servant-auth-cookie#30]
I need an endpoint where I can check if a user is authenticated. It doesn't seem to be possible without dropping down to a Raw Servant endpoint and using `getSession` on the request or changing the `authHandler`. Hope there is an easier way.

```
Api = "auth" :>
      ( Get '[JSON] (Maybe User)
       --^ can't access cookie info here(?)
  :<|> AuthProtect "cookie-auth" :> Get '[JSON] (Maybe User)
       --^ Returns 304 if no user which doesn't look great on browser
  :<|> Header "Cookie" EncryptedSession :> Get '[JSON] (Maybe User)
       --^ No instance of FromHttpApiData and decryption not straight forward
      )
```
I initially hoped to get a match on the unprotected endpoint if the protected one didn't match, but that doesn't work.

I'm on version 0.5.0.5

---

UPDATE:
I've just managed to get the info I wanted, but not obvious (to me at least) and required working directly with request headers.
```
type AuthApi = "auth" :> Header "cookie" Text :> Get '[JSON] (Maybe UserId)

authApi :: ServerT AuthApi AppHandler
authApi = authenticated

authenticated :: Maybe Text -> AppHandler (Maybe UserId)
authenticated Nothing = return Nothing
authenticated (Just h) = do
  acs <- asks appCookieSettings
  sk <- asks appServerKey
  let msession = parseSessionRequest acs [("cookie", toHeader h)]
  case msession of
    Nothing -> return Nothing
    Just sess -> do
      wm <- decryptSession acs sk sess
      return $ Just $ accountUserId $ wmData wm
```
Can I add it as an endpoint to your example? Must be a rather common usecase to check if a user is authenticated and redirect without sending a 304.

**Comment by zohl** [comment]
Hello,

sorry for making you wait, I'm finally online.


> Can I add it as an endpoint to your example? Must be a rather common usecase to check if a user is authenticated and redirect without sending a 304.

Sure, feel free to add it to the example, as it is really non-trivial piece of code. Thank you!


Nevertheless, I believe, it's possible to use some `servant`'s magic to make it simplier, like having a type combinator with two branches (for authenticated and non-authenticated cases). I'll try to think of how to implement it.
