### ISSUE TITLE
Conveniently refresh expiration time in each cookied endpoint?

### ISSUE THREAD

**Issue by michalrus** [zohl/servant-auth-cookie#37]
Hello!

How can I easily define a `cookied' = …` that will refresh expiration times on each request?

I see there’s `wmRenew`, but it’s used for *server key* renewals.

If I just `addSession` once, and then only read it using `cookied`, after expiration time, the session is expectedly invalidated.

IMO, this is quite a common use case: “expire the session after *n* minutes since last contact”.

WDYT?

**Comment by zohl** [comment]
Hello,

sounds reasonable, I think it will be possible to implement by adding a flag to cookies which tells whether they should be renewed. Will be done :)

**Comment by michalrus** [comment]
Awesome! =)

**Comment by zohl** [comment]
Hi, it's done.

Similarly to the solution of issue #35 you can specify the flag in `addSession` function like this:
`acs rs sk def { ssAutoRenew = True } session`.

**Comment by michalrus** [comment]
Brilliant!

Thank you so much! :hugs: 

I confirm this works as expected.

Thank you so much!
