### ISSUE TITLE
Allow older versions of base

### ISSUE THREAD

**Issue by mrkkrp** [zohl/servant-auth-cookie#5]
With `base >= .4.9` it's pretty unusable with current LTS.

**Comment by mrkkrp** [comment]
Tell me if it's desirable if I fix all this stuff myself and open PRs. To clarify: we want to use this in a prototype of a commercial project, and I don't have much time to wait.

**Comment by zohl** [comment]
Sure!
Feel free to open PR's, it will be appreciated a lot.

**Comment by mrkkrp** [comment]
Unfortunatelly it requires a bit more than changing bounds. See travis logs, the library only builds with GHC 7.10 at the moment. Fixing the builds is on my TODO list for today. Chances are I'll open several PRs soon.

**Comment by mrkkrp** [comment]
We'll also need to add version bounds for every package, I already found out the bounds, I'll commit and open a PR later today.

**Comment by mrkkrp** [comment]
Resolved in #12.
